name: Move Custom ingresses 
on:
  push:
    branches:
      - "master"
    paths:
      - "clusters/development/postBuild.yml"
  
jobs:
  customIngresses:
    name: Custom ingresses
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

  github-action-copy:
    uses: sondresjolyst/github-action-copy/.github/workflows/move_custom_ingresses.yml@master
    # equinor/ops-actions/.github/workflows/build-python.yml@v6.5.0