name: Move Custom ingresses 
on:
  push:
    branches:
      - "master"
    paths:
      - "clusters/development/postBuild.yml"
  workflow_dispatch:
  
jobs:
  customIngresses:
    name: Custom ingresses
    runs-on: ubuntu-22.04

    env:
      postBuild: clusters/development/postBuild.yml

    defaults:
      run:
        shell: bash

    outputs:
      ACTIVE_CLUSTER: ${{ steps.getActiveCluster.outputs.active_cluster }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get active cluster
        id: getActiveCluster
        run: echo "active_cluster=$(yq r ${{ env.postBuild }} spec.postBuild.substitute.ACTIVE_CLUSTER)" >> $GITHUB_OUTPUT
        
        # value=$(yq r database.yml test.database)`
        # echo "radix_environment=$(ls ${{ env.path }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  github-action-copy:
    uses: sondresjolyst/github-action-copy/.github/workflows/move_custom_ingresses.yml@master
    # equinor/ops-actions/.github/workflows/build-python.yml@v6.5.0